### ISSUE TITLE
Color break in pokedex border

### ISSUE THREAD

**Issue by mitchbarry** [ZachSParker/Group1PokeChess#37]
This was discovered yesterday (4/4/24) but the difference in border color when a pokemon is selected in the pokedex is because the border isn't completely opaque and the different backgrounds beneath are coming through creating a weird break in the middle near the scrollbar.

Potential fixes: 

- make the border opaque
- make an element that contains both the <div>'s with semi-transparent backgrounds to be slightly bigger by (the thickness of the border) so the semi-transparent border doesn't overlap with the semi-transparent backgrounds.

**Comment by ZachSParker** [comment]
resolved by kyle's changes
